version: '2'
services:
  web:
    build: .
    command: npm run dev
    links:
      - redis
    volumes:
      - .:/usr/src/app
    ports:
      - '3000:3000'
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgres://todoapp@postgres/todos
  postgres:
    image: postgres:9.6.2-alpine
    environment:
      POSTGRES_USER: todoapp
      POSTGRES_DB: todos
    volumes:
      - ./pgdata:/var/lib/postgresql/data
  redis:
    image: redis
    expose:
      - 6379